[resource_pack]
id = "replete"
version = "1.1.0"
supported_minecraft_version = ">=1.20 <=1.21.4"
supported_minecraft_version_name = "1.20-1.21.4"

[publishing]
curseforge_project_id = 1149488
modrinth_project_id = "JqODxgwm"

[packsquash]
source_directory = "src"
output_directory = "build"
allow_mods = ["OptiFine"]
