name: Publish

on:
  workflow_dispatch:

jobs:
  build_and_publish:
    name: Build and publish
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # A non-shallow repository clone is required for PackSquash

      - name: Get resource pack version from pack.toml
        uses: SebRollen/toml-action@v1.2.0
        id: resource_pack_version
        with:
          file: pack.toml
          field: resource_pack.version

      - name: Get supported Minecraft version from pack.toml
        uses: SebRollen/toml-action@v1.2.0
        id: supported_minecraft_version
        with:
          file: pack.toml
          field: resource_pack.supported_minecraft_version

      - name: Get supported Minecraft version name from pack.toml
        uses: SebRollen/toml-action@v1.2.0
        id: supported_minecraft_version_name
        with:
          file: pack.toml
          field: resource_pack.supported_minecraft_version_name

      - name: Print version string
        run: echo version string ${{ steps.resource_pack_version.outputs.value }}+mc${{ steps.supported_minecraft_version_name.outputs.value }}

      - name: Set release tag name environment variable
        run: echo release_tag_name=v${{ steps.resource_pack_version.outputs.value }}+mc${{ steps.supported_minecraft_version_name.outputs.value }} >> $GITHUB_ENV

      - name: Get existing release
        uses: cardinalby/git-get-release-action@v1
        id: get_existing_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ env.release_tag_name }}
          doNotFailIfNotFound: true

      - name: Check if an existing release with the same version exists
        if: steps.get_existing_release.outputs.tag_name == env.release_tag_name
        run: exit 1

      - name: Get id from pack.toml
        uses: SebRollen/toml-action@v1.2.0
        id: id
        with:
          file: pack.toml
          field: resource_pack.id

      - name: Get output directory from pack.toml
        uses: SebRollen/toml-action@v1.2.0
        id: output_directory
        with:
          file: pack.toml
          field: packsquash.output_directory

      - name: Get allowed mods from pack.toml
        uses: SebRollen/toml-action@v1.2.0
        id: allow_mods
        with:
          file: pack.toml
          field: packsquash.allow_mods

      - name: Copy resource pack files to export/
        run: |
          mkdir export/
          cp LICENSE export/LICENSE
          cp README.md export/README.md
          cp CHANGELOG.md export/CHANGELOG.md
          cp CHANGELOG_LATEST.md export/CHANGELOG_LATEST.md
          cp pack.mcmeta export/pack.mcmeta
          cp pack.png export/pack.png
          cp -r assets/ export/assets/

      - name: Create output directory
        run: |
          mkdir ${{ steps.output_directory.outputs.value }}/

      - name: Build resource pack using PackSquash
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest
          artifact_name: resource_pack
          options: |
            pack_directory = "export/"
            output_file_path = "${{ steps.output_directory.outputs.value }}/${{ steps.id.outputs.value }}-${{ steps.resource_pack_version.outputs.value }}+mc${{ steps.supported_minecraft_version_name.outputs.value }}.zip"
            allow_mods = ${{ steps.allow_mods.outputs.value }}

            ["LICENSE"]
            force_include = true

            ["**/*?.md"]
            force_include = true

      - name: Get CurseForge project ID from pack.toml
        uses: SebRollen/toml-action@v1.2.0
        id: curseforge_project_id
        with:
          file: pack.toml
          field: publishing.curseforge_project_id

      - name: Get Modrinth project ID from pack.toml
        uses: SebRollen/toml-action@v1.2.0
        id: modrinth_project_id
        with:
          file: pack.toml
          field: publishing.modrinth_project_id

      # https://github.com/marketplace/actions/mc-publish
      - name: Publish resource pack
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          # Modrinth
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-id: ${{ steps.modrinth_project_id.outputs.value }}

          name: ${{ steps.resource_pack_version.outputs.value }} (${{ steps.supported_minecraft_version_name.outputs.value }})
          github-tag: ${{ env.release_tag_name }}
          files: |
            build/*.zip
          version: ${{ env.release_tag_name }}
          version-type: release
          loaders: minecraft
          game-versions: ${{ steps.supported_minecraft_version.outputs.value }}
          modrinth-featured: false
          changelog-file: CHANGELOG_LATEST.md
